//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit_Card
    {
        public string Email { get; set; }
        public int Card_number { get; set; }
        public int Security_code { get; set; }
        public System.DateTime Expiration_date { get; set; }
        public string Card_holder_s_name { get; set; }
        public string Username { get; set; }
    }
}
